---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
    checks:
      complexity:
        enabled: false # Not something we really need to worry about.
    exclude_fingerprints:
      - c6414090fac335e67ae8283280cf335a # String prototype-read-only override
      - bdc38e86d543c7cdfff0a4850d504b48  # CodeCliamte is inaccurately thinking this is a function

  fixme:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths: []
